<script lang="ts">
    import SvelteTable from "svelte-table";
    import { configs, events, enroll, cancelEnroll } from "$lib/stores";
    import type { Config, Events, TableColumn } from "$lib/types";

    let name = $state("");
    let id = $state("");
    let deviceType = $state("");
    let showModal = $state(false);
    let filterSelections = $state({});
    let sortBy = $state("alias");
    let sortOrder = $state<-1 | 0 | 1>(1);
    let selectedRowIds = $state([]);

    const deviceTypes = ["watch", "wallet", "ipad", "phone", "airpods", "laptop", "node", "keys", "therm", "flora", "tile"];

    function generateKebabCaseId(name: string, type = "") {
        const words = name.toLowerCase().split(/\s+/);
        const filteredWords = words.filter((word) => word !== type.toLowerCase());
        return filteredWords
            .join("-")
            .replace(/[']/g, "")
            .replace(/[^a-z0-9-]+/g, "-")
            .replace(/(^-|-$)/g, "");
    }

    let modalTitle = $derived(($events as Events)?.room ? `Enroll Device - ${($events as Events).room}` : "Enroll Device");
    let autoGeneratedId = $derived(generateKebabCaseId(name));
    let tableRows = $derived($configs?.configs || []);

    function onEnroll() {
        const generatedId = deviceType ? `${deviceType}:${generateKebabCaseId(name, deviceType)}` : generateKebabCaseId(name);
        enroll(id || generatedId, name);
        showModal = false;
    }

    function onClose() {
        showModal = false;
        name = "";
        id = "";
        deviceType = "";
        cancelEnroll();
    }

    function formatRemainingTime(seconds: number) {
        const minutes = Math.floor(seconds / 60);
        const remainingSeconds = seconds % 60;
        return [minutes, remainingSeconds].map((val) => val.toString().padStart(2, "0")).join(":");
    }

    $effect(() => {
        if (($events as Events)?.state?.enrolling) showModal = true;
    });

    const columns: TableColumn<Config>[] = [
        {
            key: "alias",
            title: "Alias",
            value: (v: Config) => v.alias ?? "",
            sortable: true,
            filterOptions: (rows: Config[]) => {
                const prefixes = new Set<string>();
                rows.forEach((row) => {
                    if (row.alias) {
                        const colonIndex = row.alias.indexOf(":");
                        if (colonIndex !== -1) {
                            const prefix = row.alias.substring(0, colonIndex + 1);
                            prefixes.add(prefix);
                        }
                    }
                });
                return Array.from(prefixes)
                    .sort()
                    .map((a) => ({ name: a, value: a }));
            },
            filterValue: (v: Config) => {
                if (!v.alias) return "";
                const colonIndex = v.alias.indexOf(":");
                return colonIndex !== -1 ? v.alias.substring(0, colonIndex + 1) : "";
            },
            headerClass: "px-6 py-4 text-left text-xs font-medium text-gray-700 dark:text-gray-200 uppercase tracking-wider",
            class: "px-6 py-4",
        },
        {
            key: "id",
            title: "ID",
            value: (v: Config) => v.id ?? "",
            sortable: true,
            filterOptions: (rows: Config[]) => {
                const prefixes = new Set<string>();
                rows.forEach((row) => {
                    if (row.id) {
                        const colonIndex = row.id.indexOf(":");
                        if (colonIndex !== -1) {
                            const prefix = row.id.substring(0, colonIndex + 1);
                            prefixes.add(prefix);
                        }
                    }
                });
                return Array.from(prefixes)
                    .sort()
                    .map((a) => ({ name: a, value: a }));
            },
            filterValue: (v: Config) => {
                if (!v.id) return "";
                const colonIndex = v.id.indexOf(":");
                return colonIndex !== -1 ? v.id.substring(0, colonIndex + 1) : "";
            },
            headerClass: "px-6 py-4 text-left text-xs font-medium text-gray-700 dark:text-gray-200 uppercase tracking-wider",
            class: "px-6 py-4",
        },
        {
            key: "name",
            title: "Name",
            value: (v: Config) => v.name ?? "",
            sortable: true,
            filterOptions: (rows: Config[]) => {
                const letrs: Record<string, { name: string; value: string }> = {};
                rows.forEach((row) => {
                    const letr = row.name?.charAt(0);
                    if (letr && !letrs[letr]) {
                        letrs[letr] = {
                            name: letr.toUpperCase(),
                            value: letr.toLowerCase(),
                        };
                    }
                });
                return Object.values(letrs).sort((a, b) => a.name.localeCompare(b.name));
            },
            filterValue: (v: Config) => v.name?.charAt(0)?.toLowerCase() ?? "",
            headerClass: "px-6 py-4 text-left text-xs font-medium text-gray-700 dark:text-gray-200 uppercase tracking-wider",
            class: "px-6 py-4",
        },
        {
            key: "rssi@1m",
            title: "Rssi@1m",
            value: (v: Config) => v["rssi@1m"] ?? 0,
            renderValue: (v: Config) => (v["rssi@1m"] != null ? `${v["rssi@1m"]} dBm` : ""),
            sortable: true,
            headerClass: "px-6 py-4 text-left text-xs font-medium text-gray-700 dark:text-gray-200 uppercase tracking-wider",
            class: "px-6 py-4 whitespace-nowrap",
        },
    ];

    function classNameRow(c: Config) {
        return "";
    }
</script>

<div class="bg-gray-100 dark:bg-gray-800 rounded-lg shadow">
    <div class="p-6">
        <div class="flex justify-between items-center mb-6">
            <h2 class="text-xl font-semibold text-gray-900 dark:text-white">Devices</h2>
            <button
                onclick={() => (showModal = true)}
                class="text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-800"
            >
                Enroll
            </button>
        </div>

        {#if $configs != null}
            <div class="overflow-x-auto">
                <SvelteTable
                    {columns}
                    rows={tableRows}
                    rowKey="id"
                    bind:filterSelections
                    bind:sortBy
                    bind:sortOrder
                    selectSingle={true}
                    selectOnClick={true}
                    bind:selected={selectedRowIds}
                    classNameTable="min-w-full divide-y divide-gray-200 dark:divide-gray-700 table-auto"
                    classNameThead="bg-gray-100 dark:bg-gray-700"
                    classNameTbody="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700"
                    {classNameRow}
                    classNameRowSelected="bg-blue-50 dark:bg-blue-900"
                    classNameCell="text-sm text-gray-900 dark:text-gray-300"
                    classNameInput="mt-1 block w-full border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:border-blue-500 focus:ring-blue-500"
                    classNameSelect="mt-1 block w-full border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:border-blue-500 focus:ring-blue-500"
                />
            </div>
        {:else}
            <div class="flex items-center justify-center min-h-[50vh]">
                <div class="text-center">
                    <h1 class="text-xl font-medium text-gray-700 dark:text-gray-300">Loading configured devices...</h1>
                    <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">Please wait while we fetch the data.</p>
                </div>
            </div>
        {/if}
    </div>
</div>

{#if showModal}
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity">
        <div class="flex items-center justify-center w-full h-full p-4">
            <div class="relative bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-lg w-full">
                <div class="flex justify-between items-start p-4 border-b dark:border-gray-700">
                    <h3 class="text-xl font-semibold text-gray-900 dark:text-white">{modalTitle}</h3>
                    <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-2 ml-auto inline-flex items-center dark:hover:bg-gray-700 dark:hover:text-white" onclick={onClose}>
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        <span class="sr-only">Close</span>
                    </button>
                </div>
                <div class="p-6 space-y-6">
                    {#if !($events as Events)?.state?.enrolling}
                        {#if ($events as Events)?.state?.enrolledId}
                            <p class="text-sm leading-5 text-gray-600 dark:text-gray-400">
                                The device has been enrolled. ESPresense has disconnected; you can delete the pairing on your device. The new device ID is:
                                <span class="font-semibold text-gray-900 dark:text-white">{($events as Events).state?.enrolledId}</span>.
                            </p>
                        {:else}
                            <div class="space-y-4">
                                <select
                                    bind:value={deviceType}
                                    class="mt-1 block w-full border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                >
                                    <option value="">Select device type</option>
                                    {#each deviceTypes as type}
                                        <option value={type}>{type}</option>
                                    {/each}
                                </select>
                                <input
                                    class="mt-1 block w-full  border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                    type="text"
                                    bind:value={name}
                                    placeholder="Enter name"
                                />
                                <input
                                    class="mt-1 block w-full  border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                    type="text"
                                    bind:value={id}
                                    placeholder={name ? (deviceType ? `${deviceType}:${generateKebabCaseId(name, deviceType)}` : generateKebabCaseId(name)) : "Enter custom ID or leave empty for auto-generated"}
                                />
                                <p class="text-sm text-gray-600 dark:text-gray-400">Leave empty to use auto-generated ID</p>
                            </div>
                        {/if}
                    {:else}
                        <p class="text-sm leading-5 text-gray-600 dark:text-gray-400">To begin, navigate to your device's Bluetooth settings (on Apple Watch use the BluetoothLE app) and pair with the ESPresense device.</p>
                        <p class="mt-4 text-sm leading-5 text-gray-600 dark:text-gray-400">Start the pairing process now. Time remaining: {formatRemainingTime(($events as Events).state?.remain ?? 0)}</p>
                    {/if}
                </div>
                <div class="flex items-center justify-end p-6 space-x-4 border-t border-gray-200 dark:border-gray-700">
                    {#if !($events as Events)?.state?.enrolling && !($events as Events)?.state?.enrolledId}
                        <button
                            onclick={onEnroll}
                            disabled={!name}
                            class="text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-blue-800 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            Enroll
                        </button>
                    {/if}
                    <button
                        onclick={onClose}
                        class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>
{/if}
