"""Firmware-faithful RSSI <-> distance conversion.

Mirrors `lib/rssi_distance/rssi_distance.h::rssiToLogDistance` byte-for-byte,
so synthetic distance streams are generated by the same math the firmware
uses on-device. Any divergence between this module and the C++ helper is a
regression and is locked down by the parity test in
`tools/accuracy_harness/tests/test_firmware_model.py`.
"""

from __future__ import annotations

import math


def rssi_to_log_distance(cal_rssi: float, rssi: float, absorption: float) -> float:
    """Log-distance path-loss model (firmware canonical implementation).

    d = 10 ^ ((calRssi - rssi) / (10 * n))

    `absorption <= 0` falls back to free-space n=2.0 to match the firmware
    guard. Output unit is meters.
    """
    n = absorption if absorption > 0.0 else 2.0
    return math.pow(10.0, (cal_rssi - rssi) / (10.0 * n))


def distance_to_rssi(cal_rssi: float, distance_m: float, absorption: float) -> float:
    """Inverse log-distance: synthesize the RSSI a node *would* report at
    a given true distance, given the calibration and path-loss exponent.

    Used by the harness to start from a ground-truth (x,y) target, project
    expected RSSI for each station, inject RSSI-side noise, then run the
    same `rssi_to_log_distance` the firmware would. This makes the
    harness's noise distribution non-Gaussian-in-distance the way real
    deployments are.
    """
    if distance_m <= 0.0:
        return cal_rssi
    n = absorption if absorption > 0.0 else 2.0
    return cal_rssi - 10.0 * n * math.log10(distance_m)
