"""Versioned, deterministic report rendering.

Two outputs:
  - JSON snapshot (machine-readable, checked into reports/baseline-*.json)
  - Markdown summary (human-readable, embedded in docs/accuracy.md)
"""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Iterable

from . import __version__
from .runner import ScenarioReport


REPORT_SCHEMA_VERSION = 1


def to_json(reports: Iterable[ScenarioReport]) -> str:
    payload = {
        "schema_version": REPORT_SCHEMA_VERSION,
        "harness_version": __version__,
        "scenarios": [asdict(r) for r in reports],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def to_markdown(reports: Iterable[ScenarioReport]) -> str:
    lines: list[str] = []
    lines.append(f"<!-- Generated by accuracy_harness v{__version__}; schema v{REPORT_SCHEMA_VERSION} -->")
    lines.append("")
    for r in reports:
        lines.append(f"### Scenario: `{r.scenario}`")
        lines.append("")
        lines.append(
            f"Base seed: `{r.base_seed}` &middot; "
            f"Gaussian σ: `{r.noise['gaussian_std_db']:.1f} dB` &middot; "
            f"Multipath p: `{r.noise['multipath_probability']:.0%}` "
            f"@ `-{r.noise['multipath_attenuation_db']:.0f} dB`"
        )
        lines.append("")
        lines.append("| Track | n | Median (m) | p95 (m) | Mean (m) | Max (m) | Room mis-id |")
        lines.append("|---|---:|---:|---:|---:|---:|---:|")
        for t in r.tracks:
            lines.append(
                f"| `{t.track}` | {t.samples} | {t.median_error_m:.2f} | {t.p95_error_m:.2f} | "
                f"{t.mean_error_m:.2f} | {t.max_error_m:.2f} | {t.room_misid_rate:.1%} |"
            )
        lines.append("")
        lines.append("Single-station-outage (drop each, solve on remaining 3):")
        lines.append("")
        for t in r.tracks:
            lines.append(f"- track `{t.track}`")
            for sid, stats in sorted(t.single_station_outage.items()):
                if stats["samples"] == 0:
                    continue
                lines.append(
                    f"  - drop `{sid}`: median {stats['median_error_m']:.2f}m, "
                    f"p95 {stats['p95_error_m']:.2f}m, n={stats['samples']}"
                )
        lines.append("")
    return "\n".join(lines)
