when:
  - event: pull_request
    repo: ESPresense/ESPresense
  - event: push
    branch: main
  - event: cron
    branch: main

steps:
  - name: test-esp32
    image: ghcr.io/espresense/firmware-tester:1
    privileged: true
    depends_on: []
    volumes:
      - cache_volume:/cache
      - /dev/esp32:/dev/esp32
      - /var/lock/woodpecker:/lock
    environment:
      DEVICE: /dev/esp32
      FIRMWARE_ENV: esp32
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
      PLATFORMIO_LIBDEPS_DIR: /cache/libdeps
      PLATFORMIO_BUILD_CACHE_DIR: /cache/build_cache
      PLATFORMIO_PLATFORMS_DIR: /cache/platforms
    commands:
      - |
        flock -w 3600 /lock/esp32.lock bash -c '
          set -e
          if [ "$CI_PIPELINE_EVENT" = "pull_request" ]; then
            DURATION_SECS=${PR_DURATION_SECS:-1800}
          elif [ "$CI_PIPELINE_EVENT" = "cron" ]; then
            DURATION_SECS=${NIGHTLY_DURATION_SECS:-28800}
          else
            DURATION_SECS=${MAIN_DURATION_SECS:-28800}
          fi
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t erase -t upload
          python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
          python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS
        '

  - name: test-esp32c3
    image: ghcr.io/espresense/firmware-tester:1
    privileged: true
    depends_on: []
    volumes:
      - cache_volume:/cache
      - /dev/esp32c3:/dev/esp32c3
      - /var/lock/woodpecker:/lock
    environment:
      DEVICE: /dev/esp32c3
      FIRMWARE_ENV: esp32c3
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
      PLATFORMIO_LIBDEPS_DIR: /cache/libdeps
      PLATFORMIO_BUILD_CACHE_DIR: /cache/build_cache
      PLATFORMIO_PLATFORMS_DIR: /cache/platforms
    commands:
      - |
        flock -w 3600 /lock/esp32c3.lock bash -c '
          set -e
          if [ "$CI_PIPELINE_EVENT" = "pull_request" ]; then
            DURATION_SECS=${PR_DURATION_SECS:-1800}
          elif [ "$CI_PIPELINE_EVENT" = "cron" ]; then
            DURATION_SECS=${NIGHTLY_DURATION_SECS:-28800}
          else
            DURATION_SECS=${MAIN_DURATION_SECS:-28800}
          fi
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t erase -t upload
          python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
          python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS
        '

  - name: test-esp32c6
    image: ghcr.io/espresense/firmware-tester:1
    privileged: true
    depends_on: []
    failure: ignore
    volumes:
      - cache_volume:/cache
      - /dev/esp32c6:/dev/esp32c6
      - /var/lock/woodpecker:/lock
    environment:
      DEVICE: /dev/esp32c6
      FIRMWARE_ENV: esp32c6
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
      PLATFORMIO_LIBDEPS_DIR: /cache/libdeps
      PLATFORMIO_BUILD_CACHE_DIR: /cache/build_cache
      PLATFORMIO_PLATFORMS_DIR: /cache/platforms
    commands:
      - |
        flock -w 3600 /lock/esp32c6.lock bash -c '
          set -e
          if [ "$CI_PIPELINE_EVENT" = "pull_request" ]; then
            DURATION_SECS=${PR_DURATION_SECS:-1800}
          elif [ "$CI_PIPELINE_EVENT" = "cron" ]; then
            DURATION_SECS=${NIGHTLY_DURATION_SECS:-28800}
          else
            DURATION_SECS=${MAIN_DURATION_SECS:-28800}
          fi
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t erase -t upload
          python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
          python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS
        '

  - name: test-esp32s3
    image: ghcr.io/espresense/firmware-tester:1
    privileged: true
    depends_on: []
    volumes:
      - cache_volume:/cache
      - /dev/esp32s3:/dev/esp32s3
      - /var/lock/woodpecker:/lock
    environment:
      DEVICE: /dev/esp32s3
      FIRMWARE_ENV: esp32s3
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
      PLATFORMIO_LIBDEPS_DIR: /cache/libdeps
      PLATFORMIO_BUILD_CACHE_DIR: /cache/build_cache
      PLATFORMIO_PLATFORMS_DIR: /cache/platforms
    commands:
      - |
        flock -w 3600 /lock/esp32s3.lock bash -c '
          set -e
          if [ "$CI_PIPELINE_EVENT" = "pull_request" ]; then
            DURATION_SECS=${PR_DURATION_SECS:-1800}
          elif [ "$CI_PIPELINE_EVENT" = "cron" ]; then
            DURATION_SECS=${NIGHTLY_DURATION_SECS:-28800}
          else
            DURATION_SECS=${MAIN_DURATION_SECS:-28800}
          fi
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t erase -t upload
          python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
          python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS
        '
