when:
  - event: [push, pull_request]

steps:
  - name: test-esp32
    image: ghcr.io/espresense/firmware-tester:latest
    privileged: true
    depends_on: []
    volumes:
      - cache_volume:/cache
    environment:
      DEVICE: /dev/esp32
      FIRMWARE_ENV: esp32
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
    commands:
      - DURATION_SECS=${DURATION_SECS:-$([ "$CI_PIPELINE_EVENT" = "pull_request" ] && echo 180 || echo 28800)}
      - git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t upload
      - python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
      - python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS

  - name: test-esp32c3
    image: ghcr.io/espresense/firmware-tester:latest
    privileged: true
    depends_on: [test-esp32]
    volumes:
      - cache_volume:/cache
    environment:
      DEVICE: /dev/esp32c3
      FIRMWARE_ENV: esp32c3
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
    commands:
      - DURATION_SECS=${DURATION_SECS:-$([ "$CI_PIPELINE_EVENT" = "pull_request" ] && echo 180 || echo 28800)}
      - git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t upload
      - python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
      - python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS

  - name: test-esp32c6
    image: ghcr.io/espresense/firmware-tester:latest
    privileged: true
    depends_on: [test-esp32]
    volumes:
      - cache_volume:/cache
    environment:
      DEVICE: /dev/esp32c6
      FIRMWARE_ENV: esp32c6
      GITHUB_TOKEN:
        from_secret: github_token
      WIFI_SSID:
        from_secret: wifi_ssid
      WIFI_PASSWORD:
        from_secret: wifi_password
      PLATFORMIO_CORE_DIR: /cache/platformio
    commands:
      - DURATION_SECS=${DURATION_SECS:-$([ "$CI_PIPELINE_EVENT" = "pull_request" ] && echo 180 || echo 28800)}
      - git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - PLATFORMIO_UPLOAD_PORT=$DEVICE pio run -e $FIRMWARE_ENV -t upload
      - python3 /scripts/improv_wifi.py --port $DEVICE --ssid "$WIFI_SSID" --password "$WIFI_PASSWORD"
      - python3 /scripts/hil_monitor.py --port $DEVICE --duration $DURATION_SECS
